"""
Django settings for JustBid project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
import django_heroku
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '39-v2s!u0!ix&w(7p2d5f%48motld-le6d6ljm@s@7^q%@zo%r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition
INSTALLED_APPS = [
    'storages',
    'auction.apps.AuctionConfig',
    'django.contrib.postgres',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    "bootstrap4",
    "bootstrap_datepicker_plus",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'JustBid.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'JustBid.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'justbid',
    #     'USER': 'justbid_owner',
    #     'PASSWORD':'shireen'
    # }
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': 'ec2-54-156-149-189.compute-1.amazonaws.com',
        'NAME': 'de1c1id49i6434',
        'USER': 'glibnoxctlyxom',
        'PASSWORD': '3fe19ccbd9bba59c630b705da936b2cde83dec058e87a57cfe76822fd10f2511'
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Chicago'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = 'home'
AUTH_USER_MODEL = 'auction.Customer'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

MEDIA_ROOT = os.path.join(BASE_DIR, 'auction/media')
MEDIA_URL ='/media/'

STATIC_ROOT = os.path.join(BASE_DIR, 'auction/static')
STATIC_URL = '/static/'

## aws s3 settings to upload items dynamically
AWS_ACCESS_KEY_ID = ' AKIAIEDQLNGF5EFHVUAA'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'justbid.com'

AWS_DEFAULT_ACL = None

AWS_S3_REGION_NAME = 'us-east-2'


DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'





# Email settings for JustBid.com 8210 Assignment 3 Individual Project on Nov 2 2020
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'justbid.com404@gmail.com'
EMAIL_HOST_PASSWORD = '8210as3!'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

CRISPY_TEMPLATE_PACK = 'bootstrap4'

django_heroku.settings(locals())